version: '1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./src:/app/src
    command: ng serve --host 0.0.0.0 --poll=2000
